Development
noahhaque/bash_scripts pull request #1
Opened 2021-01-07 01:27 UTC by asimzafar202

2021-01-07 01:38 UTC, asimzafar202 commented on hello.sh
> +vdfhbfgbdfghetr
yo this doesnt look right

2021-01-07 01:41 UTC, noahhaque commented on hello.sh
> +vdfhbfgbdfghetr
comment

2021-01-07 01:42 UTC, noahhaque requested changes
look at my comment

2021-01-09 00:46 UTC, Noizebomb approved these changes
looks good

2021-01-09 00:51 UTC, merged